name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          pnpm-version: 8
          args: '--ignore-scripts --fix-lockfile'

      - name: Build
        run: pnpm run docs:build

      # 部署到 GitHub Pages
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
